[project]
name = "reddit-mcp"
version = "0.1.0"
description = "Reddit MCP Server"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Arindam Majumder"}
]
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.6.0",
    "praw"
]
